CREATE DATABASE ADBMS

USE ADBMS
--COMMENTS
CREATE TABLE TBL_AUTHOR
(
	AUTHOR_ID INT PRIMARY KEY,
	AUTHOR_NAME VARCHAR(MAX),
	COUNTRY VARCHAR(MAX)
)

CREATE TABLE TBL_BOOKS
(	
	BOOK_ID INT PRIMARY KEY,
	BOOK_TITLE VARCHAR(MAX),
	AUTHORID INT
	FOREIGN KEY (AUTHORID) REFERENCES TBL_AUTHOR(AUTHOR_ID)
)

/*
	NO IF MIN TABLES: 1
	CONDITION: ATLEAST ONE COLUMN SHOULD BE SAME

	TYPES:
		1. INNER JOIN (MATCHING RECORDS: BASED COMMON COLUMN)
		2. LEFT OUTER JOIN (LEFT TABLE WHOLE DATA + COMMON DATA)
		3. RIGHT OUTER JOIN(RIGHT TABLE WHOLE DATA + COMMON DATA)
		4. FULL OUTER JOIN (L + R + COMMON DATA)
		5. SELF JOIN (1)
		6. LEFT EXCLUSIVE JOIN
		7. RIGHT EXCLUSIVE JOIN
*/

--SYNATX: BOOK NAME
SELECT B.BOOK_TITLE AS [BOOK NAME], A.AUTHOR_NAME, A.COUNTRY
FROM TBL_BOOKS AS B
INNER JOIN
TBL_AUTHOR AS A
ON
B.AUTHORID = A.AUTHOR_ID